token:
  secretKey: your_secret_key
  refreshTime: 86400000
  expiresTime: 3600000

spring:
  application:
    name: bookstore-backend
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: wdl339
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
      #即使topic不存在，应用程序也可以正常启动
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 300

eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8040/eureka

#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: wdl339
#    key-store-type: PKCS12
#    key-alias: selfsigned_localhost_sslserver

#  zkServer.cmd
#
#  cd D:\kafka\kafka_2.13-3.8.0
#  .\bin\windows\kafka-server-start.bat .\config\server.properties
#
#  cd D:\Redis
#  .\redis-server.exe .\redis.windows.conf
#  .\redis-cli.exe flushall
#  .\redis-cli.exe shutdown