token:
  secretKey: your_secret_key
  refreshTime: 86400000
  expiresTime: 3600000

spring:
  application:
    name: bookstorebackend
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: wdl339
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
      #即使topic不存在，应用程序也可以正常启动

#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: wdl339
#    key-store-type: PKCS12
#    key-alias: selfsigned_localhost_sslserver