token:
  secretKey: your_secret_key
  refreshTime: 86400000
  expiresTime: 3600000

spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: wdl20040806
  application:
    name: bookstore-backend
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:bookstore}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:wdl339}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/cover
#    redis:
#      database: 0
#      host: localhost
#      port: 6379
#      password:
#      timeout: 300

#eureka:
#  instance:
#    prefer-ip-address: true
#    ip-address: localhost
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8040/eureka

#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: wdl339
#    key-store-type: PKCS12
#    key-alias: selfsigned_localhost_sslserver

#  zkServer.cmd
#
#  cd D:\kafka\kafka_2.13-3.8.0
#  .\bin\windows\kafka-server-start.bat .\config\server.properties
#
#  cd D:\Redis
#  .\redis-server.exe .\redis.windows.conf
#  .\redis-cli.exe flushall
#  .\redis-cli.exe shutdown
#
#  cd D:\neo4j\neo4j-community-5.26.0\bin
#  .\neo4j console
#
#  cd D:\InfluxData\influxdb
#  cmd
#  influxd
#  cd D:\InfluxData\telegraf\telegraf-1.32.3
#  cmd
#  set INFLUX_TOKEN=IA8RMuH0kBsogctbt5se0kn7j_q2Sle0uI6pVkYhpgZDboICDzB1JSozv-DO-3Qj_L4VAYhBs6haEErpEaWqdQ==
#  telegraf --config http://localhost:8086/api/v2/telegrafs/0e1078afb146f000